#! /bin/bash

set -e -o pipefail

delineate-estimate-species-partition.py  -c test01_spr0.200_.0001.json -t test01_spr0.200_.0001.nex -I  -l num_lineages:42 -l num_species:10 -l src_filepath:test01_spr0.200_.0001.nex -l true_speciation_completion_rate:0.2 -l batch_id:megaptera::20190608140057::6095311150248468009 > test01_spr0.200_.0001.partition-probs.json

python3 ../../../bin/spwd_evaluate_delineate_jobs.py test01_spr0.200_.0001.json test01_spr0.200_.0001.partition-probs.json > test01_spr0.200_.0001.joint-partition-est-perf.tsv


echo "Job $JOBID completed on $(date --rfc-3339='seconds')"
