#! /bin/bash

#$ -cwd
#$ -V
#$ -S /bin/bash


set -e -o pipefail

delineate-estimate-species-partition.py  -c test1_spr0.010_.0001.json -t test1_spr0.010_.0001.nex -I  -l num_lineages:20 -l num_species:4 -l src_filepath:test1_spr0.010_.0001.nex -l true_speciation_completion_rate:0.01 -l batch_id:megaptera::20190608133656::5593908569769541801 > test1_spr0.010_.0001.partition-probs.json

python3 ../../../bin/spwd_evaluate_delineate_jobs.py test1_spr0.010_.0001.json test1_spr0.010_.0001.partition-probs.json > test1_spr0.010_.0001.joint-partition-est-perf.tsv


echo "Job $JOBID completed on $(date --rfc-3339='seconds')"
