#! /bin/bash

set -e -o pipefail

delineate-estimate-species-partition.py  -c test01_spr0.100_.0001.json -t test01_spr0.100_.0001.nex -I  -l num_lineages:20 -l num_species:14 -l src_filepath:test01_spr0.100_.0001.nex -l true_speciation_completion_rate:0.1 -l batch_id:megaptera::20190608140318::1044052719684228286 > test01_spr0.100_.0001.partition-probs.json

python3 ../../../bin/spwd_evaluate_delineate_jobs.py test01_spr0.100_.0001.json test01_spr0.100_.0001.partition-probs.json > test01_spr0.100_.0001.joint-partition-est-perf.tsv


echo "Job $JOBID completed on $(date --rfc-3339='seconds')"
